spring:
  application:
    name: assignment-java-5
  mvc:
    view:
      prefix: /views/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/assignment_java5
    username: root
    password: "06122004"
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080
payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: 58X4B4HP
    secretKey: VRLDWNVWDNPCOEPBZUTWSEDQAGXJCNGZ
    returnUrl: http://localhost:8080/seller/thanh-toan/return
    version: 2.1.0
    command: pay
    orderType: other
